import { describe, expect, test } from 'bun:test';
import { isMetaEnvelope, pickRequirement } from '../src/motivation.ts';
import { openMemoryDb } from '../src/db.ts';
import { materializeRequirements } from '../src/requirements.ts';
import { createServer } from '../src/server.ts';
import { DEFAULT_PLANS } from '../src/config.ts';
import type { SessionMessageRow } from '../src/types.ts';

const scheduler = {
  refreshPlan: async () => ({ ok: true, slug: 'kimi', windows: [] }),
};

function messageRow(partial: Partial<SessionMessageRow> & Pick<SessionMessageRow, 'id' | 'sessionId' | 'text'>): SessionMessageRow {
  return {
    seq: 1,
    role: 'user',
    kind: 'text',
    toolName: null,
    timestamp: null,
    model: null,
    inputTokens: null,
    outputTokens: null,
    ...partial,
  };
}

describe('isMetaEnvelope', () => {
  test('真实噪音样例都被挡住', () => {
    expect(isMetaEnvelope('<recommended_plugins> Here is a list of plugins that are available but not insta…')).toBe(true);
    expect(isMetaEnvelope('<system-reminder>Auto permission mode is active</system-reminder>')).toBe(true);
    expect(isMetaEnvelope('<command-name>/sessions</command-name>')).toBe(true);
    expect(isMetaEnvelope('<local-command-stdout>done</local-command-stdout>')).toBe(true);
    expect(isMetaEnvelope('<bash-input>ls -la</bash-input>')).toBe(true);
    expect(isMetaEnvelope('Caveat: The messages below were generated by the user')).toBe(true);
    expect(isMetaEnvelope('[Request interrupted by user]')).toBe(true);
    expect(isMetaEnvelope('<task-notification>done</task-notification>')).toBe(true);
    expect(isMetaEnvelope('')).toBe(true);
    expect(isMetaEnvelope('   ')).toBe(true);
  });

  test('正常用户需求不被误伤', () => {
    expect(isMetaEnvelope('修复登录态刷新的竞态问题')).toBe(false);
    expect(isMetaEnvelope('看一下 <db.ts> 里的索引')).toBe(false);
    expect(isMetaEnvelope('compare A < B 的结果')).toBe(false);
  });
});

describe('pickRequirement', () => {
  test('跳过 ack 和信封,挑到第一条实质消息', () => {
    expect(pickRequirement([
      '可以',
      '<system-reminder>忽略我</system-reminder>',
      '把 session 目录接上需求抽取',
    ])).toBe('把 session 目录接上需求抽取');
  });

  test('titleify 截断长消息', () => {
    const long = '做'.repeat(200);
    const picked = pickRequirement([long]);
    expect(picked).not.toBeNull();
    expect(picked!.length).toBeLessThanOrEqual(81);
  });

  test('空列表 / 全是噪音返回 null', () => {
    expect(pickRequirement([])).toBeNull();
    expect(pickRequirement(['可以', '<command-name>/x</command-name>', '好'])).toBeNull();
  });
});

describe('server /api/sessions requirement', () => {
  test('requirement 字段从消息流抽取,覆盖 title 的 meta 噪音', async () => {
    const store = openMemoryDb();
    for (const plan of DEFAULT_PLANS) store.syncPlan(plan);
    const now = Date.now();
    store.upsertSessions([{
      id: 'codex:aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
      provider: 'codex',
      nativeId: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
      cwd: '/tmp/planofplan',
      title: '<recommended_plugins> Here is a list of plugins',
      sourceFile: '/tmp/rollout.jsonl',
      startedAt: now - 60_000,
      updatedAt: now - 30_000,
      inputTokens: 0,
      outputTokens: 0,
      totalTokens: 0,
      estimatedCostUsd: null,
      seenAt: now,
    }]);
    store.upsertSessionMessages([
      messageRow({ id: 'm1', sessionId: 'codex:aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', seq: 1, text: '<recommended_plugins> Here is a list of plugins that are available' }),
      messageRow({ id: 'm2', sessionId: 'codex:aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', seq: 2, text: '可以' }),
      messageRow({ id: 'm3', sessionId: 'codex:aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', seq: 3, text: '把用量页的高峰低谷标注做出来' }),
      messageRow({ id: 'm4', sessionId: 'codex:aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', seq: 4, role: 'assistant', text: '好的' }),
    ]);
    // 需求实体化后,/api/sessions 与图谱从 requirements 表读
    materializeRequirements(store);
    const response = await createServer(store, scheduler as never, { port: 9291, plans: DEFAULT_PLANS })
      .request('http://localhost/api/sessions?days=7');
    expect(response.status).toBe(200);
    const body = await response.json() as {
      sessions: Array<{ id: string; title: string | null; requirement?: string | null }>;
      graph: { nodes: Array<{ kind: string; label: string }> };
    };
    expect(body.sessions).toHaveLength(1);
    expect(body.sessions[0]?.requirement).toBe('把用量页的高峰低谷标注做出来');
    // graph 的 requirement 节点也用抽取结果
    const reqNode = body.graph.nodes.find((node) => node.kind === 'requirement');
    expect(reqNode?.label).toBe('把用量页的高峰低谷标注做出来');
  });

  test('消息表里没有该 session 时 requirement 为 null', async () => {
    const store = openMemoryDb();
    for (const plan of DEFAULT_PLANS) store.syncPlan(plan);
    const now = Date.now();
    store.upsertSessions([{
      id: 'claude:bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
      provider: 'claude',
      nativeId: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
      cwd: '/tmp',
      title: '旧目录行',
      sourceFile: '/tmp/x.jsonl',
      startedAt: now - 60_000,
      updatedAt: now - 30_000,
      inputTokens: 0,
      outputTokens: 0,
      totalTokens: 0,
      estimatedCostUsd: null,
      seenAt: now,
    }]);
    const response = await createServer(store, scheduler as never, { port: 9291, plans: DEFAULT_PLANS })
      .request('http://localhost/api/sessions?days=7');
    const body = await response.json() as { sessions: Array<{ requirement?: string | null }> };
    expect(body.sessions[0]?.requirement).toBeNull();
  });
});
